const fs = require('fs');
const path = require('path');

const DATA_DIR = path.join(__dirname, '..', 'Data');
const OUT_FILE = path.join(__dirname, '..', 'js', 'data.js');

const files = fs.readdirSync(DATA_DIR).filter(f => f.endsWith('.csv'));
const datasets = [];
const seen = new Set();

for (const file of files) {
  const raw = fs.readFileSync(path.join(DATA_DIR, file), 'utf-8');
  const lines = raw.trim().split('\n').map(l => l.replace(/\r$/, ''));
  const header = lines[0];

  const headerParts = parseCSVRow(header);
  const terms = headerParts.slice(1);

  const key = terms.join('|');
  if (seen.has(key)) continue;
  seen.add(key);

  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    const parts = parseCSVRow(lines[i]);
    const date = parts[0];
    const values = parts.slice(1).map(v => {
      const n = parseInt(v, 10);
      return isNaN(n) ? 0 : n;
    });
    rows.push({ date, values });
  }

  if (terms.length === 1) {
    datasets.push({
      term: terms[0],
      multiTerm: false,
      data: rows.map(r => ({ date: r.date, value: r.values[0] }))
    });
  } else {
    datasets.push({
      terms: terms,
      multiTerm: true,
      data: rows.map(r => {
        const point = { date: r.date };
        terms.forEach((t, i) => { point[t] = r.values[i]; });
        return point;
      })
    });
  }
}

function parseCSVRow(line) {
  const parts = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        current += ch;
      }
    } else {
      if (ch === '"') {
        inQuotes = true;
      } else if (ch === ',') {
        parts.push(current);
        current = '';
      } else {
        current += ch;
      }
    }
  }
  parts.push(current);
  return parts;
}

const js = `// AUTO-GENERATED by scripts/build-data.js — do not edit\nconst DATASETS = ${JSON.stringify(datasets, null, 2)};\n`;
fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, js, 'utf-8');
console.log(`Written ${datasets.length} datasets to js/data.js`);
